/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equipo29.tema5.Vistas;

import equipo29.tema5.Conexion.VacunatorioData;
import equipo29.tema5.Data.Vacunatorio;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 20352555674
 */
public class ABMVacunatorios extends javax.swing.JInternalFrame {

    private VacunatorioData cvd;

    /**
     * Creates new form ABMVacunatorio
     */
    public ABMVacunatorios(VacunatorioData cvd) {
        initComponents();
        this.cvd = cvd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        alta = new javax.swing.JButton();
        baja = new javax.swing.JButton();
        modificacion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        id2 = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();

        jLabel1.setText("ID");

        jLabel2.setText("Descipcion");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        alta.setText("Alta");
        alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActionPerformed(evt);
            }
        });

        baja.setText("Baja");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });

        modificacion.setText("Mod.");
        modificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificacionActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        id2.setVisible(false);
        id2.setEditable(false);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(alta))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descripcion))
                        .addGap(9, 9, 9)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(baja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alta)
                    .addComponent(baja)
                    .addComponent(modificacion)
                    .addComponent(salir)
                    .addComponent(limpiar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        if (!id.getText().isEmpty()) {
            try {
                Vacunatorio vacunatorio = cvd.buscarVacunatorioId(Integer.parseInt(id.getText()));
                descripcion.setText(vacunatorio.getDescripcion());
                id2.setText(id.getText());
            } catch (NullPointerException ex) {
            }
        } else if (!descripcion.getText().isEmpty()) {
            try {
                Vacunatorio vacunatorio = cvd.buscarVacunatorioDescipcion(descripcion.getText());
                id.setText(vacunatorio.getIdVacunatorio() + "");
                id2.setText(id.getText());
            } catch (NullPointerException ex) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Indique el ID o el nombre para realizar la busqueda");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActionPerformed
        // TODO add your handling code here:
        if (id.getText().isEmpty() && !descripcion.getText().isEmpty()) {
            try {
                cvd.guardarVacunatorio(new Vacunatorio(descripcion.getText(), true));
            } catch (SQLException ex) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Complete solo la Descripcion");
        }

    }//GEN-LAST:event_altaActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        // TODO add your handling code here:
        if (!id.getText().isEmpty()) {
            try {
                cvd.bajaVacunatorio(Integer.parseInt(id.getText()));
            } catch (SQLException ex) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Realice la busqueda del Vacunatorio previemente a producir la baja");
        }
    }//GEN-LAST:event_bajaActionPerformed

    private void modificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificacionActionPerformed
        // TODO add your handling code here:
        if (id.getText().isEmpty() || descripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Realice la busqueda del Vacunatorio previemente a modificarlo");
        } else {
            Vacunatorio vacunatorio = new Vacunatorio();
            vacunatorio.setIdVacunatorio(Integer.parseInt(id.getText()));
            vacunatorio.setDescripcion(descripcion.getText());
            try {
                cvd.modificarVacunatorio(vacunatorio, Integer.parseInt(id2.getText()));
                {
                }
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_modificacionActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        id.setText("");
        id2.setText("");
        descripcion.setText("");
    }//GEN-LAST:event_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta;
    private javax.swing.JButton baja;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificacion;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
