/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equipo29.tema5.Vistas;

import equipo29.tema5.Conexion.CiudadanoData;
import equipo29.tema5.Data.Ciudadano;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruce
 */
public class Registro extends javax.swing.JInternalFrame {

    private CiudadanoData cd;

    /**
     * Creates new form Registro
     */
    public Registro(CiudadanoData cd) {
        initComponents();
        this.cd = cd;
        cargarComboPatologias();
        cargarComboAmbitoLaboral();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dnilabel = new javax.swing.JLabel();
        nombreyapellidolabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        Celularlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        nombreyapellido = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pato = new javax.swing.JComboBox<>();
        al = new javax.swing.JComboBox<>();

        dnilabel.setText("dni");

        nombreyapellidolabel.setText("Nombre y Apellido");

        emaillabel.setText("Email");

        Celularlabel.setText("Celular");

        jLabel1.setText("Patologia preexistente");

        jLabel2.setText("Ambito laboral");

        dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniKeyTyped(evt);
            }
        });

        nombreyapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreyapellidoKeyTyped(evt);
            }
        });

        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        id.setEditable(false);
        id.setVisible(false);

        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dnilabel)
                            .addComponent(nombreyapellidolabel)
                            .addComponent(emaillabel)
                            .addComponent(Celularlabel))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dni)
                            .addComponent(nombreyapellido)
                            .addComponent(email)
                            .addComponent(celular, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pato, 0, 186, Short.MAX_VALUE)
                                .addComponent(al, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(registrar)
                        .addGap(36, 36, 36)
                        .addComponent(modificar)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(buscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dnilabel)
                            .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreyapellidolabel)
                            .addComponent(nombreyapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emaillabel)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Celularlabel)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(pato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar)
                    .addComponent(modificar)
                    .addComponent(jButton1)
                    .addComponent(salir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        if (dni.getText().isEmpty() || nombreyapellido.getText().isEmpty() || email.getText().isEmpty() || celular.getText().isEmpty()
                || pato.getSelectedItem().toString().isEmpty() || al.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete los campos requeridos");
        } else if (dni.getText().length() < 7 || dni.getText().length() > 8) {
            JOptionPane.showMessageDialog(null, "El documento debe tener entre 7 y 8 digitos de longitud");
        } else if (celular.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Verificar numero de celular ingresado");
        } else {
            try {
                if (pato.getSelectedItem().toString().equalsIgnoreCase("no aplica")) {
                    cd.guardarCiudadano(new Ciudadano(Integer.parseInt(dni.getText()), nombreyapellido.getText(), email.getText(), celular.getText(), null, al.getSelectedItem().toString()));
                } else {
                    cd.guardarCiudadano(new Ciudadano(Integer.parseInt(dni.getText()), nombreyapellido.getText(), email.getText(), celular.getText(), pato.getSelectedItem().toString(), al.getSelectedItem().toString()));
                }
                jButton1ActionPerformed(evt);
            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        if (dni.getText().isEmpty() || nombreyapellido.getText().isEmpty() || email.getText().isEmpty() || celular.getText().isEmpty()
                || pato.getSelectedItem().toString().isEmpty() || al.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete los campos requeridos");
        } else if (dni.getText().length() < 7 || dni.getText().length() > 8) {
            JOptionPane.showMessageDialog(null, "El documento debe tener entre 7 y 8 digitos de longitud");
        } else if (celular.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Verificar numero de celular ingresado");
        } else {
            try {
                Ciudadano ciudadano = new Ciudadano();
                ciudadano.setId(Integer.parseInt(id.getText()));
                ciudadano.setDni(Integer.parseInt(dni.getText()));
                ciudadano.setNombreCompleto(nombreyapellido.getText());
                ciudadano.setEmail(email.getText());
                ciudadano.setCelular(celular.getText());

                ciudadano.setAmbitoTrabajo(al.getSelectedItem().toString());
                if (pato.getSelectedItem().toString().equalsIgnoreCase("no aplica")) {
                    ciudadano.setPatologia(null);
                } else {
                    ciudadano.setPatologia(pato.getSelectedItem().toString());
                }
                cd.modificarCiudadano(ciudadano);

            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
        if (!dni.getText().isEmpty()) {
            Ciudadano ciudadano = cd.buscarCiudadanoDni(Integer.parseInt(dni.getText()));
            nombreyapellido.setText(ciudadano.getNombreCompleto());
            email.setText(ciudadano.getEmail());
            celular.setText(ciudadano.getCelular());
            al.setSelectedItem(ciudadano.getAmbitoTrabajo());
            pato.setSelectedItem(ciudadano.getPatologia());
            id.setText(ciudadano.getId() + "");
        }  else if (!email.getText().isEmpty()) {
            Ciudadano ciudadano = cd.buscarCiudadanoEmail(email.getText());
            dni.setText(ciudadano.getDni() + "");
            nombreyapellido.setText(ciudadano.getNombreCompleto());
            email.setText(ciudadano.getEmail());
            celular.setText(ciudadano.getCelular());
            pato.setSelectedItem(ciudadano.getPatologia());
            al.setSelectedItem(ciudadano.getAmbitoTrabajo());
            id.setText(ciudadano.getId() + "");
        } else if (!celular.getText().isEmpty()) {
            Ciudadano ciudadano = cd.buscarCiudadanoCelular(celular.getText());
            dni.setText(ciudadano.getDni() + "");
            nombreyapellido.setText(ciudadano.getNombreCompleto());
            email.setText(ciudadano.getEmail());
            celular.setText(ciudadano.getCelular());
            pato.setSelectedItem(ciudadano.getPatologia());
            al.setSelectedItem(ciudadano.getAmbitoTrabajo());
            id.setText(ciudadano.getId() + "");
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Documento, email o celular valido del ciudadano para realizar una busqueda");
        }
        
        if(dni.getText().charAt(0)== ' '|| dni.getText().charAt(dni.getText().length()-1)==' '||email.getText().charAt(0)== ' '|| email.getText().charAt(email.getText().length()-1)==' '||celular.getText().charAt(0)== ' '|| celular.getText().charAt(celular.getText().length()-1)==' '){
                System.out.println("Hay espacios en blanco");
        }
        
        }catch (NullPointerException ex){
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Elimine los espacios vacíos.");
        }catch (StringIndexOutOfBoundsException ex){
            System.out.println("no se completó ningun campo");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_dniKeyTyped

    private void nombreyapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreyapellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_nombreyapellidoKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyTyped

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dni.setText("");
        nombreyapellido.setText("");
        email.setText("");
        celular.setText("");
        id.setText("");
        pato.setSelectedItem("");
        al.setSelectedItem("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celularlabel;
    private javax.swing.JComboBox<String> al;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel dnilabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombreyapellido;
    private javax.swing.JLabel nombreyapellidolabel;
    private javax.swing.JComboBox<String> pato;
    private javax.swing.JButton registrar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    private void cargarComboPatologias() {
        pato.addItem("");
        pato.addItem("no aplica");
        pato.addItem("asma");
        pato.addItem("diabetes");
        pato.addItem("cardiopatia");
        pato.addItem("obesidad");
        pato.addItem("oncologico");
    }

    private void cargarComboAmbitoLaboral() {
        al.addItem("");
        al.addItem("desempleado");
        al.addItem("estudiante");
        al.addItem("salud");
        al.addItem("educacion");
        al.addItem("seguridad");
        al.addItem("comercio");
        al.addItem("otro");
    }
}
